server:
  port:
    8050

spring:
  application:    name: API-Gateway  cloud:    gateway:
      default-filters:      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:        cors-configurations:          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"      routes:
      - id: user
        uri: lb://user-service
        predicates:
        - Path=/user/**
      - id: catalog
        uri: lb://catalog-service
        predicates:
        - Path=/catalog/**
      - id: cart
        uri: lb://cart-service
        predicates:
        - Path=/cart/**
      - id: order
        uri: lb://order-service
        predicates:
        - Path=/order/**
          main:    web-application-type: reactive